version: 0.2

env:
  parameter-store:
    NPM_TOKEN: "code-build-prod-npm-publish-token"

phases:
  install:
    commands:
    - echo Nothing to do in commands phase...
  pre_build:
    commands:
    - echo Nothing to do in the pre_build phase...
  build:
    commands:
    - echo Build started on `date`
    - sudo npm install
  post_build:
    commands:
    - sudo echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - sudo npm whoami
    - sudo npm publish --access public
    - echo Build completed on `date`

